### PR TITLE
Added custom error if error_get_last() does not return anything.

### PR DESCRIPTION
**Pull request by empi89**
The set_error_handler function in the Application __construct method eats errors from file_get_contents. In this case box shows only a "[RuntimeException]" without any further hint and terminates. It was very frustrating to not see that I had a wrong path to my main-file in the box.json :-(.

Sorry that there is no test case for that in the PR. Phpunit has a custom error handler too and does not let you define own handlers. However without overwriting the handler there is no error for that I could test.

### CODE REVIEW

**Comment by ghost** [comment]
Sorry to have done this, but I was in the middle of working on Box 3.0.

Could you please re-do your changes on the 2.0 branch?

I had also created a new [contribution guide](https://github.com/kherge/Box/blob/master/CONTRIBUTING.md), so if you could read it too I would really appreciate it!

**Comment by empi89** [comment]
Yes I could do so but I see only the master, gh-pages and 1.0 branch in this repo. Thanks for your contribution guide but I didn't see what I have done wrong. Could you please explain it in more detail?

**Comment by ghost** [comment]
Unfortunately the branch was created after you had already forked Box.

You can find the [2.0 branch](https://github.com/kherge/Box/tree/2.0) on the original repository.

I think GitHub allows you to specify which branch to submit the PR to, so you might want to close this PR and submit a new one.

EDIT: As for the contribution guide, I think your submission looks fine! I should have worded my request a little better, more of a "heads up" than "you did something wrong".

**Comment by empi89** [comment]
I have created a new pull request https://github.com/kherge/Box/pull/62 on this and hopefully have used the correct branch now. 

No problem about the wording ;-). Thanks for your great software!

**Pull request closed without merging**
