### PR TITLE
Allow to use Symfony 3.x components

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
ping @kherge

**Comment by keradus** [comment]
anyone ?

**Comment by keradus** [comment]
ping @kherge

**Comment by jameshalsall** [comment]
@kherge any chance of getting this merged today?

**Comment by keradus** [comment]
no

**Comment by kherge** [comment]
:\ Sorry it took so long to get any sort of response.

**Comment by jameshalsall** [comment]
Thanks

**Comment by keradus** [comment]
@kherge 
maybe, if you cannot administrate the project yourself, consider to add some other guys to do it as well? so repo be dead...

**Pull request merged**
