### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @cordoval!

Why should the `.idea` directory be removed from the ignore list?

**Comment by cordoval** [comment]
http://www.craftitonline.com/2013/10/ignore-symfony2-phpstorm-files-like-a-pro-with-global-ignoring/

**Comment by ghost** [comment]
Okay, that seems like a good idea!

Remove `/*.iml` from the list too and I'll merge it.

**Comment by cordoval** [comment]
what is the .iml for? just curious

**Comment by ghost** [comment]
I use IntelliJ IDEA, which is what PhpStorm is based on.

The `*.iml` file is the project file used by IDEA, in addition to the .idea cache directory.

**Comment by ghost** [comment]
Thanks again!

**Pull request merged**
